### ISSUE TITLE
Bug in Game/Player H-index?

### ISSUE THREAD

**Issue by zoki666** [ccomeaux/boardgamegeek4android#112]
I have played 7 times to Railroad Ink (this is my most played), but I don't see in my Game H-index (I only see games that I played 6 or less times). Plays are synced.

**Comment by Vinne2** [comment]
I also don't see all my plays below the H-index, but I think there's a thought behind that.

Now, my game H-index is 5 ("5.82" in app release 6.7, which shows rational H-index) and on the list (below the H-index) I can see:
- 2 games played 6x
- 2 games played 5x (and these have grey background)
- 1 game played 3x

I believe the list shows only the games which are played [H-index] times (in my case: 5x) and additionally games which are played once more (in my case: 6x) and games played once less (would be 4x, but in my case is 3x, because I haven't played any game exactly 4x). And those games played [H-index] times have grey background.

The same theory suits my player H-index – I have H-indeex 7 ("7.67" in ap release 6.7) and one the list I can see (in short): 2 players "13x", 5 players "7x" and 4 players "6x".

Would that suit your case, too? I guess your game H-index is 5 or less.

@ccomeaux is that correct?

**Comment by ccomeaux** [comment]
Yes, you are mostly correct. The app shows the games at or around your h-index. It is not intended to show all games - you can get this from the collection view with the proper sort order. The intent was to give you an idea of what makes up your h-index.

**Comment by ccomeaux** [comment]
@zoki666 I don't follow your issue. Are you able to add a screenshot?

**Comment by zoki666** [comment]
![Screenshot_20191028-084240](https://user-images.githubusercontent.com/28391248/67669444-2bec3880-f972-11e9-9d1b-2a55f77ec40f.jpg)

Here you can see it. It occurs in Game H-index and Player H-Index too. This runs with 6.7.0

**Comment by Vinne2** [comment]
That is correct AFAIK.
1) Your Game H-index = 5.91 → so under Game H-index you can see games which you played [H or H±1 times] → (in your case: 4 and 5 and 6 times).
2) The same with Player H-index = 4.67 → so it shows:
- players you played with 4 times
- first closest player that you plaued less than 4 times (2 in your case)
- first closest player that you plaued more than 4 times (14 in your case)

**Comment by zoki666** [comment]
Ah ok!!!! understood.
