### ISSUE TITLE
Unsuccessful post: 307

### ISSUE THREAD

**Issue by jmclean27** [ccomeaux/boardgamegeek4android#172]
I am getting an error message that reads, Unsuccessful post: 307
I don't know how to fix this issue?

**Comment by Vlan13** [comment]
Same problem for me since monday

**Comment by goldeneyeonline** [comment]
This is a duplicate issue, please see under resolved

**Comment by jmclean27** [comment]
Mine started Sunday the 23rd jan 2022Sent from my Galaxy
-------- Original message --------From: Vlan13 ***@***.***> Date: 2022-01-27  1:27 p.m.  (GMT-07:00) To: ccomeaux/boardgamegeek4android ***@***.***> Cc: jmclean27 ***@***.***>, Author ***@***.***> Subject: Re: [ccomeaux/boardgamegeek4android] Unsuccessful post: 307 (Issue #172) 
Same problem for me since monday

**Comment by jmclean27** [comment]
I'm new to this site and after looking around, I can't find the resolution for this issue, I can't even find a section alley resolved? Just need a little help to get pointed in the right direction. Thanks

**Comment by goldeneyeonline** [comment]
If with "this site" you mean github... It's also under "issues" but there's a sub-tab for "resolved". The issue has been fixed in the code, but a new version / release has yet to be built. So it doesn't make sense to open another issue when the issue is already fixed in the codebase. We just got to wait for a new build :-)

**Comment by jmclean27** [comment]
Awsome, thank you, ill collect this and wait for the new build. Thanks again.

**Comment by goldeneyeonline** [comment]
No worries man, have a good one!
