### ISSUE TITLE
Merge players

### ISSUE THREAD

**Issue by dkniffin** [ccomeaux/boardgamegeek4android#51]
It would be nice to have a way to merge two players, or add a geekbuddy account for a player. I started logging plays with a friend, before adding his BGG account, so now I have two players for him.

**Comment by oddityoverseer13** [comment]
The manual workaround for this right now, is to go back to each game and add a username to the player. It wasn't too bad in my case, since I only logged a few games that way, but it could be a very large headache otherwise.

All this feature has to do is find all games for a user, and edit them to have a username.

**Comment by ccomeaux** [comment]
Fixed in 5.2.
