### ISSUE TITLE
Sorting is not preserved when navigating back to collection page

### ISSUE THREAD

**Issue by quasipedia** [ccomeaux/boardgamegeek4android#76]
**Version**: 6.4.2

**Steps to reproduce**:
1. go to collection
2. sort with any other sorting rule than "name"
3. click on a game
4. click on the back button

**Expected behaviour**: collection to be sorted according to the previously selected sorting key

**Actual behaviour**: collection is sorted again by "name" (the default)

**Comment by tupaschoal** [comment]
Weird, I tried this multiple times with multiple sorting options and couldn't reproduce ):
(I'm also on 6.4.2)

Which Android version are you using?

**Comment by quasipedia** [comment]
7.1.1 patch level 5 March.
Could you try by setting your collection to contain "played" games only? That's the only thing I can think of, when I think to what may set me apart from the typical user...

**Comment by tupaschoal** [comment]
No luck still. Tried on my phone (Android 5ish) and on emulator with 7+. ):

**Comment by quasipedia** [comment]
Is there anything _you_ want to test me then, to see what's the triggering condition?

**Comment by quasipedia** [comment]
[I posted the question over at the BGG forum](https://boardgamegeek.com/article/25480528#25480528) and I'm definitively not the only one with this problem, but I also realised that maybe you were using the *phone* back button instead than the *app* back button?

**Comment by ccomeaux** [comment]
This is working as designed (see #78).

**Comment by Vinne2** [comment]
I still se this behavior. 

Version: 6.7.1
Android 9

Steps to reproduce:

1. go to Collection
2. sort or filter the Collection (any other rule than "Name")
3. click on a game
4. click on the back button (phone Back button or in-app Up button)

Expected behaviour: view collection still filtered/sorted (according to the previously selected sorting/filter rules)

Actual behaviour: collection is sorted again by "Name" (the default)

**Comment by Vinne2** [comment]
Screen video showing the behavior.
https://youtu.be/0UQL6UROvfc (unpublic)

**Comment by Vinne2** [comment]
@tupaschoal @ccomeaux have you seen the video form comment above? Is this designed behavior? @quasipedia do you still see this issue? I really think this Issue should be reopened. Or should I open a new one?

**Comment by quasipedia** [comment]
This is super-interesting @Vinne2 .  The bug is **not there** if one uses the "system back button" the one at the bottom of the screen, the recurved arrow.  The bug is **still there** if one clicks on the top-left arrow on the screen, what I would call "in-app back button".  So yes... this issue is not yet _fully_ resolved... (tested on v.6.6.7)

**Comment by quasipedia** [comment]
@Vinne2 - I just wrote a message about he "in app" and "system" back buttons behaving differently... and then I realised that @ccomeaux already answered this over 2 years ago... I agree with you that this feels like a UX bug, but Chris feels otherwise and already declared the app works "as per design" (see the thread in #78), so...  ¯\_(ツ)_/¯
(The app is great anyway, this feels like a minor thing)

**Comment by corkysru** [comment]
For me it doesn't even keep sorts or filters if I switch apps. 
It's very annoying when trying to check things in multiple apps.

**Comment by Vinne2** [comment]
@quasipedia I know about the #78 and I'm not talking about this (BTW in my case they behave the same, but never mind). In my case sorting and filters aren't preserved if I use either "phone Back button or in-app Up button", as I've written few comments above.  My question here is neither "why isn't it preserved" nor "which button is which" but "how can I come back from a game details to the list/collection to see if still sorted/filtered?". Because neither Up nor Back button work.
